In [1]:
import os
import pickle
import numpy as np
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.


In [2]:
BASE_DIR            = os.path.dirname(os.getcwd())
MODEL_SAVE_PATH =  os.path.join(BASE_DIR, 'models', 'test-spam-filter.h5')
TOKENIZER_SAVE_PATH =  os.path.join(BASE_DIR, 'models', 'tokenizer.pkl')

In [7]:
# This is using the same tokenizer as the training model.
tokenizer, MAX_SEQUENCE_LENGTH = pickle.load(open(TOKENIZER_SAVE_PATH, 'rb'))

In [8]:
# this load the trained model
model = load_model(MODEL_SAVE_PATH)

In [9]:
def predict(text):
    txt = [text]
    txt = tokenizer.texts_to_sequences(txt)
    txt = pad_sequences(txt, maxlen=MAX_SEQUENCE_LENGTH, dtype='int32', value=0)
    probs = model.predict(txt, batch_size=1, verbose=2)[0]
    best = np.argmax(probs)
    return probs, best, "%.2f%% likelihood"%(probs[best] * 100)

In [10]:
predict("What a nice surprise!")

(array([2.6508796e-04, 9.9973494e-01], dtype=float32), 1, '99.97% likelihood')

In [11]:
predict("Last minute sale on all CELL phones in the UK now. Get urs free")

(array([0.9731119 , 0.02688811], dtype=float32), 0, '97.31% likelihood')

In [12]:
predict("call for a free double plan")

(array([0.50484633, 0.49515375], dtype=float32), 0, '50.48% likelihood')